version: "2.1"
services:
  registry:
    build: ./registry
    volumes:
      - registry-data:/data
    environment:
      - CONFD_BACKEND=ENV
      - REGISTRY_STORAGE_PATH=/data
    cap_add:
      - SYS_RESOURCE
      - SYS_ADMIN
    security_opt:
      - 'seccomp:unconfined'
    tmpfs:
      - /sys/fs/cgroup
    # # This doesn't work on supervisor v9.14.0
    # # Have to go to >= v9.14.4, or <=v9.11.0
    # ports:
    #   - "80:80"
    # # This is only needed if `ports` above cannot be used
    network_mode: host

  legacy-docker:
    build: ./legacy-docker
    privileged: true

volumes:
  registry-data:
